[phases.setup]
# Railway'in varsayılan paketlerine sadece bzip2 ekle.
# Bu, en başta karşılaştığımız phantomjs hatasını çözer.
nixPkgs = ["...", "bzip2"]

# Varsayılan Nginx yapılandırmasını kendi özel yapılandırmamızla değiştir.
cmds = ["cp default.conf /etc/nginx/conf.d/default.conf"]
