[global]
pid = /run/php/php-fpm.pid
error_log = /dev/stderr

[www]
; Standart ve güvenli web sunucusu kullanıcısı.
user = www-data
group = www-data

; Nginx'in bağlanacağı soket dosyası.
listen = /run/php/php-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Performans ayarları
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Logları konteyner log akışına yönlendir.
access.log = /dev/stdout
clear_env = no 