[global]
pid = /run/php/php-fpm.pid
error_log = /dev/stderr

[www]
; Konteyner ortamında basitlik ve uyumluluk için root olarak çalıştır.
user = root
group = root

; Nginx'in bağlanacağı soket dosyası.
listen = /run/php/php-fpm.sock
listen.owner = root
listen.group = root
listen.mode = 0660

; Performans ayarları
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Logları konteyner log akışına yönlendir.
access.log = /dev/stdout
clear_env = no 